CREATE TABLE USER
(
    ID         BIGSERIAL,
    FIRST_NAME VARCHAR(100) NOT NULL,
    LAST_NAME  VARCHAR(100) NOT NULL,
    ID_NUMBER  INTEGER      NOT NULL,

    CONSTRAINT USER_PK PRIMARY KEY (ID)
);

CREATE TABLE USER_CONTACT
(
    ID      BIGSERIAL,
    USER_ID BIGINT,
    CODE    VARCHAR(21) NOT NULL,
    VALUE   VARCHAR(50) NOT NULL,

    CONSTRAINT USER_CONTACT_PK PRIMARY KEY (ID),
    CONSTRAINT USER_CONTACT_USER_FK FOREIGN KEY (USER_ID) REFERENCES USER (ID)
);